# To edit secret files, run `nix run nixpkgs#sops -- secrets/secrets.yaml`
keys:
  # cat /etc/ssh/ssh_host_ed25519_key.pub | nix run nixpkgs#ssh-to-age
  # gpg --list-public-keys --with-colons | grep fpr | awk -F: '{print $10}' | head -n1
  - &openpgp 9C635181306E1D7FEA53858775DB252683B07650
  - &Proteus-NUC age1mfs3eh0zwpxse06x5dwg78rp3wmpxe8ag3yvkwmkkgrx7gpea96qglanyz
  - &Proteus-MBP14M4P age1g550pxhfzh6rtj76t6v7dzyrzy02g0kuqz27adml8eq7zw6l4adqvx4pm5
  - &Proteus-Desktop age1yv5rv2s3pgc0pxy03c560lz746s9r2qp3exzqq5m3equ5yjtsexscja2r9
  - &Proteus-NixOS-0 age1tmn54vwdelxz8axt0pkl35z6anumvu4fjm2lw5xnzt8xdudl95jqgm5992
  - &Proteus-NixOS-1 age1ez48xcmyfrl9y6ueuvhfc9drutj0r228cfs43t9uvphuyv4v6ygsy7gp4l
  - &Proteus-NixOS-2 age100tjlvhw66afqa2qkzywsywgg9hrwn2h3yuucxuvqprmnp0739vqtxlfl3
  - &Proteus-NixOS-3 age10u3w4a973l83fv8t7ndx9nzyuj993m6vrjxvf6xw9lvxm9rkwgdst862j7
  - &Proteus-NixOS-4 age1n0n20r3cal54arpwhq5g2n7ds5gc4ju9vl065a09nnp0qfsq4uvqu6j0wz
  - &Proteus-NixOS-5 age1t4vxw6s8sw64uk7g927gvwrj48uaakgaj54w0ke5hs87t20e8eys30nfvm
# TIP: To rotate a encrypted file with new recipients
# updatekeys secrets/syncthing_proteus-nuc.priv.pem.age
# TIP:Use recovery key if lost access to secret keys
# SOPS_AGE_KEY=$(nix run nixpkgs#ssh-to-age -- -private-key -i ~/path/to/recovery.priv.key)
creation_rules:
## BEGIN Common
  - path_regex: secrets/common\.sops\.yaml$
    key_groups:
      - pgp: [*openpgp]
        age:
          - *Proteus-NUC
          - *Proteus-MBP14M4P
          - *Proteus-Desktop
          - *Proteus-NixOS-0
          - *Proteus-NixOS-1
          - *Proteus-NixOS-2
          - *Proteus-NixOS-3
          - *Proteus-NixOS-4
          - *Proteus-NixOS-5
  - path_regex: secrets/sb_client_linux\.json\.sops$
    key_groups:
      - pgp: [*openpgp]
        age: [*Proteus-NUC, *Proteus-Desktop]
  - path_regex: secrets/sb_client_darwin\.json\.sops$
    key_groups:
      - pgp: [*openpgp]
        age: [*Proteus-MBP14M4P]
  - path_regex: secrets/proteus_server\.priv\.pem\.sops$
    key_groups:
      - pgp: [*openpgp]
        age: [*Proteus-NUC, *Proteus-MBP14M4P, *Proteus-Desktop]
## END Common
## BEGIN GCP Compute Engines
  - path_regex: secrets/sb_Proteus-NixOS-1\.json\.sops$
    key_groups:
      - pgp: [*openpgp]
        age:
          [*Proteus-NixOS-0, *Proteus-NixOS-1, *Proteus-NixOS-2, *Proteus-NixOS-3, *Proteus-NixOS-4, *Proteus-NixOS-5]
## END GCP Compute Engines
## BEGIN Proteus-NUC
  - path_regex: secrets/Proteus-NUC\.sops\.yaml$
    key_groups:
      - pgp: [*openpgp]
        age: [*Proteus-NUC]
  - path_regex: secrets/authelia_oidc_rsa\.pem.sops$
    key_groups:
      - pgp: [*openpgp]
        age: [*Proteus-NUC]
## END Proteus-NixOS
## BEGIN Proteus-Desktop
  - path_regex: secrets/Proteus-Desktop\.sops\.yaml$
    key_groups:
      - pgp: [*openpgp]
        age: [*Proteus-Desktop]
  - path_regex: secrets/Proteus-Desktop_syncthing\.priv\.pem\.sops$
    key_groups:
      - pgp: [*openpgp]
        age: [*Proteus-Desktop]
## END Proteus-Desktop
## BEGIN Trusted Machines (HM)
  # NOTE: for user secrets host ssh key cannot be accessed by a regular user
  - path_regex: secrets/nix_secret\.key\.sops$
    key_groups:
      - pgp: [*openpgp]
        age: [*Proteus-NUC, *Proteus-MBP14M4P]
  - path_regex: secrets/aws_credentials\.sops\.yaml$
    key_groups:
      - pgp: [*openpgp]
        age: [*Proteus-NUC]
## END Trusted Machines (HM)
## BEGIN Proteus-NUC (HM)
  # TIP: Encrypt in-place since sops matches inputs files for `path_regex`
  # sops encrypt -i secrets/syncthing_proteus-nuc.priv.pem.age
  # TIP: To edit, run
  # SOPS_AGE_KEY=$(nix run nixpkgs#ssh-to-age -- -private-key -i ~/Secrets/Backup/proteus@agenix-recovery.ssh.priv.key) sops -- edit secrets/syncthing_proteus-nuc.priv.pem.age
  - path_regex: secrets/Proteus-NUC_syncthing\.priv\.pem\.sops$
    key_groups:
      - pgp: [*openpgp]
        age: [*Proteus-NUC]
## END Proteus-NUC (HM)
## BEGIN Proteus-MBP14M4P (HM)
  # Encrypt in-place since sops matches inputs files for `path_regex`
  # sops encrypt -i secrets/syncthing_proteus-nuc.priv.pem.age
  # To edit, run
  # SOPS_AGE_KEY=$(nix run nixpkgs#ssh-to-age -- -private-key -i ~/Secrets/Backup/proteus@agenix-recovery.ssh.priv.key) sops -- edit secrets/syncthing_proteus-nuc.priv.pem.age
  - path_regex: secrets/Proteus-MBP14M4P_syncthing\.priv\.pem\.sops$
    key_groups:
      - pgp: [*openpgp]
        age: [*Proteus-MBP14M4P]
## END Proteus-MBP14M4P (HM)
