# To edit secret files, run `nix run nixpkgs#sops -- secrets/secrets.yaml`
keys:
  # cat /etc/ssh/ssh_host_ed25519_key.pub | nix run nixpkgs#ssh-to-age
  # gpg --list-public-keys --with-colons | grep fpr | awk -F: '{print $10}' | head -n1
  - &openpgp 9C635181306E1D7FEA53858775DB252683B07650
  - &Proteus-NUC age1mfs3eh0zwpxse06x5dwg78rp3wmpxe8ag3yvkwmkkgrx7gpea96qglanyz
  - &Proteus-MBP14M4P age1g550pxhfzh6rtj76t6v7dzyrzy02g0kuqz27adml8eq7zw6l4adqvx4pm5
  - &Proteus-Desktop age1yv5rv2s3pgc0pxy03c560lz746s9r2qp3exzqq5m3equ5yjtsexscja2r9
  - &Proteus-NixOS-0 age1tmn54vwdelxz8axt0pkl35z6anumvu4fjm2lw5xnzt8xdudl95jqgm5992
  - &Proteus-NixOS-1 age1ez48xcmyfrl9y6ueuvhfc9drutj0r228cfs43t9uvphuyv4v6ygsy7gp4l
# TIP: To rotate a encrypted file with new recipients
# updatekeys secrets/syncthing_proteus-nuc.priv.pem.age
# TIP:Use recovery key if lost access to secret keys
# SOPS_AGE_KEY=$(nix run nixpkgs#ssh-to-age -- -private-key -i ~/path/to/recovery.priv.key)
creation_rules:
## BEGIN Common
  - path_regex: secrets/common\.sops\.yaml$
    key_groups:
      - pgp: [*openpgp]
        age: [*Proteus-NUC, *Proteus-MBP14M4P, *Proteus-Desktop]
  - path_regex: secrets/sb_client_linux\.json\.sops$
    key_groups:
      - pgp: [*openpgp]
        age: [*Proteus-NUC, *Proteus-MBP14M4P, *Proteus-Desktop]
## END Common
## BEGIN Proteus-NUC
  - path_regex: secrets/paperless\.sops\.yaml$
    key_groups:
      - pgp: [*openpgp]
        age: [*Proteus-NUC]
## END Proteus-NixOS
## BEGIN Trusted Machines (HM)
  # NOTE: for user secrets host ssh key cannot be accessed by a regular user
  - path_regex: secrets/nix_secret\.key\.sops$
    key_groups:
      - pgp: [*openpgp]
        age: [*Proteus-NUC, *Proteus-MBP14M4P]
  - path_regex: secrets/aws_credentials\.sops\.yaml$
    key_groups:
      - pgp: [*openpgp]
        age: [*Proteus-NUC]
## END Trusted Machines (HM)
## BEGIN Proteus-NUC (HM)
  # Encrypt in-place since sops matches inputs files for `path_regex`
  # sops encrypt -i secrets/syncthing_proteus-nuc.priv.pem.age
  # To edit, run
  # SOPS_AGE_KEY=$(nix run nixpkgs#ssh-to-age -- -private-key -i ~/Secrets/Backup/proteus@agenix-recovery.ssh.priv.key) sops -- edit secrets/syncthing_proteus-nuc.priv.pem.age
  - path_regex: secrets/Proteus-NUC_syncthing\.priv\.pem\.sops$
    key_groups:
      - pgp: [*openpgp]
        age: [*Proteus-NUC]
## END Proteus-NUC (HM)
