{pkgs, config, lib, mylib, myvars, ...}:
with lib; let
  cfg = config.modules.desktop.wayland;
in {
  imports = mylib.scan_path ./.;

  options.modules.desktop.wayland.enable = mkEnableOption "Wayland Display Server";

  config = (mkIf cfg.enable {
    xdg.portal = {
      enable = true;
      wlr.enable = true;
      extraPortals = with pkgs; [
        xdg-desktop-portal-wlr
      ];
    };

    services = {
      xserver.enable = false; # disable xorg server
      # https://wiki.archlinux.org/title/Greetd
      greetd = {
        enable = true;
        settings = {
          default_session = {
            # Wayland Desktop Manager is installed only for user ryan via home-manager!
            user = myvars.username;
            # .wayland-session is a script generated by home-manager, which links to the current wayland compositor(sway/hyprland or others).
            # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
            command = "$HOME/.wayland-session"; # start a wayland session directly without a login manager
            # command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --cmd $HOME/.wayland-session";  # start wayland session with a TUI login manager
          };
        };
      };
    };
  });
}
