{config, myvars, lib, ...}: let
  server_pub_crt = "${myvars.secrets_dir}/proteus_server.pub.pem";
  tailnet = "tailba6c3f.ts.net";
  openldap_port = lib.removeSuffix "/" (lib.last (lib.strings.splitString
    ":" (lib.head config.services.openldap.urlList))
  );
  authelia_port = lib.last (lib.strings.splitString
    ":"
    config.services.authelia.instances.main.settings.server.address
  );
in {
  networking.firewall = {
    allowedTCPPorts = [
      80 # Traefik
      443 # Traefik
      636 # OpenLDAP (secure)
      853 # BIND DoT
    ];
    allowedUDPPorts = [
      443 # Traefik (QUIC)
      # 636 # OpenLDAP (secure, generally not used)
      # 853 # unbound DNS-over-QUIC, bind don't support it
    ];
  };
  age.secrets."traefik_server.priv.pem" = {
    file = "${myvars.secrets_dir}/proteus_server.priv.pem.age";
    mode = "0400";
    owner = config.systemd.services.traefik.serviceConfig.User;
  };
  services.traefik = {
    enable = true;
    # Static configuration handles entrypoints (ports) and global settings
    staticConfigOptions = {
      global = {checkNewVersion = false; sendAnonymousUsage = false;};
      api.dashboard = true;
      entryPoints = {
        # Force HTTP to HTTPS redirect globally
        web = {address = ":80"; http.redirections.entryPoint = {to = "websecure"; scheme = "https";};};
        websecure = {
          address = ":443";
          http3 = {}; # For QUIC
          # Prevent large video uploads from timing out and throwing Error 499.
          # Ref: https://web.archive.org/web/20260217103328/https://docs.immich.app/administration/reverse-proxy/#traefik-proxy-example-config
          transport.respondingTimeouts = {readTimeout = "600s"; idleTimeout = "600s";};
          # Trust Tailscale IPs to ensure X-Forwarded-* headers
          # (like X-Forwarded-Method) generated by Traefik on other nodes
          # (e.g., Proteus-Desktop) are preserved and not dropped for security
          # reasons.
          forwardedHeaders.trustedIPs = [
            myvars.networking.hosts_addr.Proteus-Desktop.ipv4
            myvars.networking.hosts_addr.Proteus-Desktop.ipv6
          ];
        };
        # Dedicated entrypoint for secure LDAP traffic
        ldaps = {address = ":636";};
        # Add the standard DoT port as a TCP entrypoint
        dot = {address = ":853";};
      };
    };
    # Dynamic configuration defines routing rules, backend services, and certificate management.
    dynamicConfigOptions = {
      # Establish the default fallback certificate.
      # This is critical for TCP clients (like `ldapsearch`) that do not send
      # Server Name Indication (SNI) data during the TLS handshake. Without this,
      # Traefik serves an untrusted dummy certificate.
      tls.stores.default.defaultCertificate = {
        certFile = server_pub_crt; keyFile = config.age.secrets."traefik_server.priv.pem".path;
      };
      # For other domains
      # tls.certificates = [{certFile = server_pub_crt; keyFile = config.age.secrets."traefik_server.priv.pem".path;}];
      http = {
        # For sunshine-webui
        serversTransports.ignorecert.insecureSkipVerify = true;

        middlewares.authelia-auth.forwardAuth = {
          # Tell Traefik where to ask if a user is authenticated
          address = "http://127.0.0.1:${authelia_port}/api/authz/forward-auth?authelia_url=https://auth.${myvars.domain}/";
          trustForwardHeader = true;
          authResponseHeaders = ["Remote-User" "Remote-Groups" "Remote-Email" "Remote-Name"];
        };
        routers = {
          # Router for the login portal
          # `tls = {}` enables TLS using the default cert provided above
          authelia = {
            rule = "Host(`auth.${myvars.domain}`)"; entryPoints = ["websecure"]; service = "authelia-backend"; tls = {};
          };
          traefik-dashboard = {
            rule = "Host(`traefik.${myvars.domain}`)";
            entryPoints = ["websecure"];
            # Protect the dashboard
            middlewares = ["authelia-auth"];
            service = "api@internal";
            tls = {};
          };
          atuin = {
            rule = "Host(`atuin.${myvars.domain}`)"; entryPoints = ["websecure"]; service = "atuin"; tls = {};
          };
          immich = {
            rule = "Host(`immich.${myvars.domain}`)"; entryPoints = ["websecure"]; service = "immich"; tls = {};
          };
          paperless = {
            rule = "Host(`paperless.${myvars.domain}`)"; entryPoints = ["websecure"]; service = "paperless"; tls = {};
          };
          # sftpgo-webui = {
          #   rule = "Host(`sftpgo.${myvars.domain}`)"; entryPoints = ["websecure"]; service = "sftpgo-webui"; tls = {};
          # };
          # sftpgo-webdav = {
          #   rule = "Host(`webdav.${myvars.domain}`)"; entryPoints = ["websecure"]; service = "sftpgo-webdav"; tls = {};
          # };
          aria2-rpc = {
            rule = "Host(`aria2.${myvars.domain}`)"; entryPoints = ["websecure"]; service = "aria2-rpc"; tls = {};
          };
          qinglong = {
            rule = "Host(`ql.${myvars.domain}`)"; entryPoints = ["websecure"]; service = "qinglong"; tls = {};
          };
          doh = {
            # Intercept standard DoH queries at the apex domain
            rule = "(Host(`${myvars.domain}`) || Host(`ns1.${myvars.domain}`) || Host(`proteus-nuc.${tailnet}`)) && Path(`/dns-query`)";
            entryPoints = ["websecure"];
            tls = {}; # Traefik decrypts the HTTPS traffic
            service = "doh";
          };
          sb = {
            rule = "Host(`sb.${myvars.domain}`)";
            entryPoints = ["websecure"];
            middlewares = ["authelia-auth"];
            service = "sb-dashboard";
            tls = {};
          };
          syncthing = {
            rule = "Host(`syncthing.${myvars.domain}`)";
            entryPoints = ["websecure"];
            middlewares = ["authelia-auth"];
            service = "syncthing-dashboard";
            tls = {};
          };
          home-assistant = {
            rule = "Host(`hass.${myvars.domain}`)"; entryPoints = ["websecure"]; service = "home-assistant"; tls = {};
          };
          sunshine-webui = {
            rule = "Host(`sunshine.${myvars.domain}`)";
            entryPoints = ["websecure"]; service = "sunshine-webui"; tls = {};
          };
          papra = {rule = "Host(`papra.${myvars.domain}`)"; entryPoints = ["websecure"]; service = "papra"; tls = {};};
          notebook = {
            rule = "Host(`notebook.${myvars.domain}`)"; entryPoints = ["websecure"]; service = "notebook"; tls = {};
          };
          forgejo = {
            rule = "Host(`git.${myvars.domain}`)"; entryPoints = ["websecure"];  service = "forgejo";  tls = {};
          };
        };
        services = {
          authelia-backend.loadBalancer.servers = [{url = "http://127.0.0.1:${authelia_port}";}];
          atuin.loadBalancer.servers = [
            {url = "http://127.0.0.1:${builtins.toString config.services.atuin.port}";}
          ];
          immich.loadBalancer.servers = [
            {url = "http://127.0.0.1:${builtins.toString config.services.immich.port}";}
          ];
          paperless.loadBalancer.servers = [
            {url = "http://127.0.0.1:${builtins.toString config.services.paperless.port}";}
          ];
          # sftpgo-webui.loadBalancer.servers = [
          #   {url = "http://127.0.0.1:${builtins.toString (builtins.head config.services.sftpgo.settings.httpd.bindings).port}";}
          #   {url = "http://[::1]:${builtins.toString (builtins.head config.services.sftpgo.settings.httpd.bindings).port}";}
          # ];
          # sftpgo-webdav.loadBalancer.servers = [
          #   {url = "http://127.0.0.1:${builtins.toString (builtins.head config.services.sftpgo.settings.webdavd.bindings).port}";}
          #   {url = "http://[::1]:${builtins.toString (lib.last config.services.sftpgo.settings.webdavd.bindings).port}";}
          # ];
          # Even though it's WebSockets, we define it as http://
          aria2-rpc.loadBalancer.servers = [{
            url = "http://127.0.0.1:${builtins.toString config.services.aria2.settings.rpc-listen-port}";
          }];
          qinglong.loadBalancer.servers = [{url = "http://127.0.0.1:5700";}];
          # Use HTTP/2 Cleartext (h2c) when talking to BIND's local port.
          doh.loadBalancer.servers = [{url = "h2c://127.0.0.1:8053";} {url = "h2c://[::1]:8053";}];
          sb-dashboard.loadBalancer.servers = [{url = "http://127.0.0.1:9091";}];
          syncthing-dashboard.loadBalancer = {
            # By setting to false Traefik will overrides the Host header to
            # 127.0.0.1
            passHostHeader = false;
            servers = [{url = "http://${config.home-manager.users.${myvars.username}.services.syncthing.guiAddress}";}];
          };
          home-assistant.loadBalancer.servers = let
            hass_port = builtins.toString config.services.home-assistant.config.http.server_port;
          in [{url = "http://127.0.0.1:${hass_port}";} {url = "http://[::1]:${hass_port}";}];
          sunshine-webui.loadBalancer = {
            serversTransport = "ignorecert";
            servers = [{url = "https://127.0.0.1:${builtins.toString (config.services.sunshine.settings.port + 1)}";}];
          };
          papra.loadBalancer.servers = [{url = "http://127.0.0.1:1221";}];
          notebook.loadBalancer.servers = [{
            url = let
              attrset_find_first_name = key: set: builtins.elemAt
                (lib.attrsets.attrNames set)
                (lib.lists.findFirstIndex (i: lib.strings.hasInfix key i) null (lib.attrsets.attrNames set));
              port = lib.lists.last (
                lib.strings.splitString
                  ":"
                  (attrset_find_first_name "notebook.${myvars.domain}" config.services.caddy.virtualHosts)
              );
            in "http://127.0.0.1:${port}";
          }];
          forgejo.loadBalancer.servers = [{
            url = "http://127.0.0.1:${builtins.toString config.services.forgejo.settings.server.HTTP_PORT}";
          }];
        };
      };
      tcp = {
        routers = {
          # Catch-all for traffic on this port. standard LDAP clients (like
          # ldapsearch and many older legacy systems) do not send SNI data.
          openldap-secure = {
            rule = "HostSNI(`*`)";
            entryPoints = ["ldaps"];
            service = "openldap-backend";
            tls = {};
          };
          dot = {
            rule = "HostSNI(`${myvars.domain}`) || HostSNI(`ns1.${myvars.domain}`) || HostSNI(`proteus-nuc.${tailnet}`)";
            entryPoints = ["dot"];
            service = "dot";
            tls = {};
          };
        };
        services = {
          openldap-backend.loadBalancer = {
            # Instruct Traefik to inject the PROXY protocol v2 header
            proxyProtocol.version = 2;
            servers = [
              {address = "127.0.0.1:${openldap_port}";}
              {address = "[::1]:${openldap_port}";}
            ];
          };
          # Forward raw DNS to BIND's local 53
          dot.loadBalancer = {
            proxyProtocol.version = 2;
            servers = [{address = "127.0.0.1:8530";}{address = "[::1]:8530";}];
          };
        };
      };
    };
  };
}
