args@{
  lib,
  pkgs,
  mylib,
  ...
}:
rec {
  username = "proteus";
  userFullName = "Proteus Qian";
  email = "sudaku233@outlook.com";
  nixosStateVersion = "26.05";
  darwinStateVersion = 7;
  githubUsername = "magic0whi";
  secretsDir = mylib.relativeToRoot "secrets";

  city = "Suzhou, China";
  latitude = "31.3113626";
  longitude = "121.5020943";
  timeZone = "Asia/Taipei"; # Main timezone

  monospace = {
    name = "Iosevka Nerd Font Mono";
    package = pkgs.nerd-fonts.iosevka;
  };

  # Initial Hashed Password is used for the first-run only, as I use OpenLDAP to manage cross-OS autnenticate
  # Generated by `mkpasswd -m scrypt`
  initial_hashed_password = "$7$CU..../....ok6SfTAfNaBUnQ96VKt.Y.$e6xJ04cp782zzn07DNj7PtvteiEbpzKyeWibpkQIXX.";

  # Public Keys that can be used to login to all my PCs, Macbooks, and servers.
  #
  # Since its authority is so large, we must strengthen its security:
  # 1. The corresponding private key must be:
  #    1. Generated locally on every trusted client via:
  #      ```bash
  #      # KDF: bcrypt with 256 rounds, takes 2s on Apple M2):
  #      # Passphrase: digits + letters + symbols, 12+ chars
  #      ssh-keygen -t ed25519 -a 256 -C "ryan@xxx" -f ~/.ssh/xxx`
  #      ```
  #    2. Never leave the device and never sent over the network.
  # 2. Or just use hardware security keys like Yubikey/CanoKey.
  sshAuthorizedKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHBAm5d2IeApyfv8zLb7IMpex7wVHkCV86ztON7HFTkn openpgp:0xB17F9ED3"
  ];
  gitSigningKey = "73EDF7A727CC3B5F329863DBFC4881A7361DF34E";
  # Use an [A]uthenticate subkey, run `gpg --list-secret-keys --with-keygrip` to show its keygrip
  gpgKeygrip = [ "94BDB192359497927D5AA4AC76D238BA1BFEFE57" ];

  catppuccin = {
    flavor = "mocha";
    accent = "pink";
  };

  storagePath = "/mnt/storage/data";
  storage2Path = "/mnt/storage/data2";

  backupTimes = {
    forgejo = "02:00";
    paperless = "02:15";
    psql = "02:20";
    restic = "03:00";
  };

  workspaces = [
    "0other"
    "1terminal"
    "2browser"
    "3chat"
    "4gaming"
    "5music"
    "6file"
    "7design"
    "8vm"
    "9"
  ];

  sb.ruleSetCfg = {
    urlPrefix = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing";
    defaultCfg = {
      type = "remote";
      format = "binary";
      http_client = "Default"; # Auto works poor
    };
  };

  nixCache = rec {
    hostname = "Proteus-Desktop";
    url = "https://nix-cache.${hostname}.s3-pub.${domain}";
    publicKey = "${hostname}.s3.${domain}-1:IxrRwk4uC5ittHeG9menkuajABnrX9cboEWwZz/m4+E=";
  };

  domain = "proteus.eu.org";
  tailnet = "tailba6c3f.ts.net";
  networking = import ./networking.nix args;

  syncthing = ./syncthing.nix; # Usage: imports = [ const.syncthing ];

  mkResticBackupsCfg = import ./restic.nix lib username backupTimes.restic;
}
