name: Nix Check
description: Run Nix Flake Checks
inputs:
  system:
    description: "System to check"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v22

    - name: Magic Nix Cache
      if: github.server_url == 'https://github.com'
      uses: DeterminateSystems/magic-nix-cache-action@v13

    - name: Proteus' Nix Cache
      if: github.server_url != 'https://github.com'
      shell: bash
      run: |
        sed -i -e 's|^\(extra-substituters\ = \)|\1https://s3.proteus.eu.org/nix-cache/ |' \
        -e 's|^\(extra-trusted-public-keys\ =\ \)|\1s3.proteus.eu.org-1:IxrRwk4uC5ittHeG9menkuajABnrX9cboEWwZz/m4+E= |' \
        /etc/nix/nix.conf

    - name: Run nix flake check
      shell: bash
      run: |
        nix run \
          --inputs-from . \
          nixpkgs#nix-fast-build -- \
          --skip-cached --no-nom \
          --flake "./#checks.${{ inputs.system }}.mylib_tests"
