name: Check Nix Flake
on: [push]
jobs:
  check-linux:
    name: Run Flake checks (${{ matrix.system }})
    strategy:
      fail-fast: false # Don't cancel other matrix jobs if one fails
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          # - os: ubuntu-24.04-arm
          #   system: aarch64-linux
          - os: ubuntu-latest
            system: riscv64-linux
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6.0.2
      - name: Run Nix Check
        uses: ./.github/actions/nix-check
        with:
          system: ${{ matrix.system }}
  check-macos:
    name: Run Flake checks (aarch64-darwin)
    # Only run macOS checks on GitHub, skip them on Forgejo
    if: github.server_url == 'https://github.com'
    # Use a dynamic runs-on so Forgejo doesn't hang waiting for a macos runner before evaluating the `if` condition
    runs-on: ${{ github.server_url == 'https://github.com' && 'macos-latest' || 'ubuntu-latest' }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6.0.2
      - name: Run Nix Check
        uses: ./.github/actions/nix-check
        with:
          system: aarch64-darwin
