name: Check Nix Flake
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6.0.2

      - name: Install Nix
        uses: cachix/install-nix-action@v31.10.4
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Magic Nix Cache
        if: github.server_url == 'https://github.com'
        uses: DeterminateSystems/magic-nix-cache-action@v13

      # Proteus' Nix Cache (For self-hosted runners like Forgejo/Gitea)
      - name: Proteus' Nix Cache
        if: github.server_url != 'https://github.com'
        run: |
          mkdir -p ~/.config/nix
          cat <<EOF >> ~/.config/nix/nix.conf
          extra-substituters = https://s3.proteus.eu.org/nix-cache/
          extra-trusted-public-keys = s3.proteus.eu.org-1:IxrRwk4uC5ittHeG9menkuajABnrX9cboEWwZz/m4+E=
          EOF

      # # Debug
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3.23
      # You can also try https://upterm.dev/

      - name: Run nix flake check
        run: nix flake check --show-trace --verbose
