name: Check Nix Flake
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6.0.2

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Run nix flake check
        run: nix flake check --show-trace --verbose --system $(nix eval --raw --impure --expr 'builtins.currentSystem')
