# This file is not imported into your NixOS configuration. It is only used for the agenix CLI.
# agenix use the public keys defined in this file to encrypt the secrets.
# and users can decrypt the secrets by any of the corresponding private keys.
let
  # A key for recovery purpose, generated by `ssh-keygen -t ed25519 -a 256 -C "proteus@agenix-recovery"` with a strong passphrase and keeped it offline in a safe place.
  recovery_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGNgO0PQwXRThE8+2ZkSU8FFDCDkCBD2FJPumvjsigFo proteus@agenix-recovery";
  # For opengpg, run:
  # gpg --list-secret-keys --keyid-format short
  # gpg --export-ssh-key <subkey_with_[A]>\!
  opengpg = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHBAm5d2IeApyfv8zLb7IMpex7wVHkCV86ztON7HFTkn openpgp:0xB17F9ED3";
  # Get system's ssh public key by command:
  #   cat /etc/ssh/ssh_host_ed25519_key.pub
  # If you do not have this file, you can generate all the host keys by command:
  #   sudo ssh-keygen -A
  Proteus-NUC = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGkreuZakzaKdfQL+YNAvcr6WRsIz5c3eoFcK3NAUmLu root@Proteus-NUC";
  Proteus-Desktop = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJla2bgFUIxlMyfqiS/BIxkFXFiIh4dhjjOvWzHnr6IL root@Proteus-Desktop";
  Proteus-NixOS-1 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGqgfVyb6hCdQmzbls0NNjMJ6Zxp3zq+XClR1OZIPnCD root@Proteus-NixOS-1";
  Proteus-NixOS-2 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM1+VCgRXwuoKpKGMBSDdcCeTyVj8Z0jL056tmKM+Rxg root@Proteus-NixOS-2";
  Proteus-NixOS-3 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGj2Cf9faGKcaakEsBRCAGUaj42zYpjJPjycHeqhxdxK root@Proteus-NixOS-3";
  Proteus-NixOS-4 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC0ZPECWe2QmB5QqQhBIloXP8lkpBEhpcUPnnVIuKbNU root@Proteus-NixOS-4";
  Proteus-NixOS-5 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILKbjjsPGhQrkrH5HKXMR6rTRJ3pV5+a9ca7GvQ7GvsH root@Proteus-NixOS-5";
  Proteus-NixOS-6 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOUXCE7Ghu4cLl0xBCg+q69QqGuhyIu17KDgrCpz0Gvb root@Proteus-NixOS-6";
  machines = [recovery_key opengpg];
  google_vps = [
    Proteus-NixOS-1
    Proteus-NixOS-2
    Proteus-NixOS-3
    Proteus-NixOS-4
    Proteus-NixOS-5
  ];
  huawei_vps = [Proteus-NixOS-6];
in {
  # To see & edit encrypted file, run:
  # agenix -e sb_client.json.age -i <(pgp2ssh <<< <(gpg -ao - --export-secret-subkeys subkey_with_[A]\!) <<< 1 2>&1 | awk 'BEGIN { A=0; S=0; } /BEGIN OPENSSH PRIVATE KEY/ { A=1; } { if (A==1) { print; } }')
  "sb_client.json.age".publicKeys = machines;
  "sb_client_linux.json.age".publicKeys = machines ++ [Proteus-NUC Proteus-Desktop];
  "syncthing_Proteus-MBP14M4P.priv.pem.age".publicKeys = machines;
  "syncthing_proteus-nuc.priv.pem.age".publicKeys = machines ++ [Proteus-NUC];
  "syncthing_proteus-desktop.priv.pem.age".publicKeys = machines ++ [Proteus-Desktop];
  "proteus_server.priv.pem.age".publicKeys = machines ++ [Proteus-NUC] ++ google_vps ++ huawei_vps;
  "aria2rpc.priv.age".publicKeys = machines ++ [Proteus-NUC];
  "sb_Proteus-NixOS-1.json.age".publicKeys = machines ++ google_vps;
  "sb_Proteus-NixOS-6.json.age".publicKeys = machines ++ huawei_vps;
  "proteus-ap.key.age".publicKeys = machines ++ [Proteus-Desktop];
  "minio.env.age".publicKeys = machines ++ google_vps ++ huawei_vps;
  "atuin.env.age".publicKeys = machines ++ [Proteus-NUC];
  "immich.env.age".publicKeys = machines ++ [Proteus-NUC];
}
