# This file is not imported into your NixOS configuration. It is only used for the agenix CLI.
# agenix use the public keys defined in this file to encrypt the secrets.
# and users can decrypt the secrets by any of the corresponding private keys.
let
  # A key for recovery purpose, generated by `ssh-keygen -t ed25519 -a 256 -C "proteus@agenix-recovery"` with a strong passphrase and keeped it offline in a safe place.
  recovery_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGNgO0PQwXRThE8+2ZkSU8FFDCDkCBD2FJPumvjsigFo proteus@agenix-recovery";
  # For opengpg, run:
  # gpg --list-secret-keys --keyid-format short
  # gpg --export-ssh-key <subkey_with_[A]>\!
  opengpg = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHBAm5d2IeApyfv8zLb7IMpex7wVHkCV86ztON7HFTkn openpgp:0xB17F9ED3";
  # Get system's ssh public key by command:
  #   cat /etc/ssh/ssh_host_ed25519_key.pub
  # If you do not have this file, you can generate all the host keys by command:
  #   sudo ssh-keygen -A
  Proteus-NixOS-3 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIApKI/t64l+gbXUkUgYaEmH5MibN7q6W2ZcreNaTjd6N proteus@Proteus-NixOS-3";
  Proteus-NixOS-4 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDR5ZoOvgTtQIgCv+Bt0gF9AlCUE0zM1sofmuZppWdaY root@Proteus-NixOS-4";
  machines = [recovery_key opengpg];
  oracle_vps = [Proteus-NixOS-3 Proteus-NixOS-4];
in {
  # To see & edit encrypted file, run:
  # agenix -e sb_client.json.age -i <(pgp2ssh <<< <(gpg -ao - --export-secret-subkeys subkey_with_[A]\!) <<< 1 2>&1 | awk 'BEGIN { A=0; S=0; } /BEGIN OPENSSH PRIVATE KEY/ { A=1; } { if (A==1) { print; } }')
  "sb_client.json.age".publicKeys = machines;
  "proteus_smb.priv.age".publicKeys = machines;
  "syncthing_Proteus-MBP14M4P.priv.pem.age".publicKeys = machines;
  "syncthing_proteus-nuc.priv.pem.age".publicKeys = machines;
  "proteus_server.priv.pem.age".publicKeys = machines;
  "aria2rpc.priv.age".publicKeys = machines;
  "sb_Proteus-NixOS-3.json.age".publicKeys = machines ++ oracle_vps;
}
